### ISSUE TITLE
sample of data

### ISSUE THREAD

**Issue by dionman** [hwwang55/GraphGAN#1]
Hi,
Thanks for sharing the code!
Could you please upload a sample of the data used in your experiments to see the entire workflow of the technique? Or alternately the format of the data that the model requires? It's hard to do experiments without having some information about this

**Comment by hwwang55** [comment]
Thanks for your interest. We are still reorganizing the code of GraphGAN, and we plan to upload the arXiv-GrQc dataset, as well as a README file, in a few days.

**Comment by hwwang55** [comment]
Thanks for your interest. We are still reorganizing the code of GraphGAN, and we plan to upload the arXiv-GrQc dataset, as well as a README file, in a few days.
