### ISSUE TITLE
A serious BUG?

### ISSUE THREAD

**Issue by wanjunhong0** [hwwang55/GraphGAN#13]
When I try to print loss for D and G, I find after first epoch there is no input into training any more. 
I think the problem in the for loop. 
If you want as the comments said generate new nodes every inter epoch, then you should delete if statement. Because that only generate on the first epoch. After that the input is rewrite to empty vector from second epoch. 
Or you can put initialized empty vector out of for loop and use that input for every epoch.
That might be we all cant reproduce the results you presented in your paper. 
Hope this got fixed. 

    # D-steps
    for d_epoch in range(config.n_epochs_dis):
        center_nodes = []
        neighbor_nodes = []
        labels = []

        # generate new nodes for the discriminator for every dis_interval iterations
        if d_epoch % config.dis_interval == 0:
           center_nodes, neighbor_nodes, labels = self.prepare_data_for_d()

**Comment by hwwang55** [comment]
Bug fixed. Thanks a lot for your comment.
