### ISSUE TITLE
请问节点分类的数据集是使用哪一个呢？可以共享吗？

### ISSUE THREAD

**Issue by liutongyang** [hwwang55/GraphGAN#21]
巨佬您好，我超崇拜您！近两年来一直在仰望您！您在Paperweekly的分享中提到过，GraphGAN中节点是无属性且不带标签的，冒昧请教一下，paper的节点分类数据集是使用的哪一个，如何做的呢？在GraphGAN中添加属性和标签是否具有可行性呢？恳请不吝赐教！liutongyang1995@gmail.com

**Comment by hwwang55** [comment]
你好，感谢你对我们工作的兴趣！节点分类的数据集是BlogCatalog和Wikipedia，具体的做法在文章中也都有描述。添加属性和标签需要重新设计模型，理论上当然是可行的。谢谢！

**Comment by liutongyang** [comment]
感谢您的细心回复！我看到代码中，G和D各自train了一个WordEmbedding文件，link_predicion任务也是分别取这两个矩阵计算精读，请问，这两个矩阵可以做融合吗？G和D使用一个矩阵可以吗？
