### ISSUE TITLE
Error in code

### ISSUE THREAD

**Issue by A4AppleB4Ball** [hwwang55/GraphGAN#4]
https://github.com/hwwang55/GraphGAN/blob/b56ed5c1593c49472eb84eab9d8c6c6714a523b9/src/GraphGAN/graph_gan.py#L355

Hi,
In this line, generator embedding is written in discriminator and vice versa.
Can you please verify ?

**Comment by hwwang55** [comment]
Thanks for your comment. We have fixed the error.
