### ISSUE TITLE
What are the major updates in new code

### ISSUE THREAD

**Issue by ayushgoyaal** [hwwang55/GraphGAN#6]
In the earlier version of your code I was getting better accuracies on various datasets I tried.
**Was there something wrong in your previous code?**
Can you please tell me the changes made by you.

**Comment by hwwang55** [comment]
There is no major update in the new code, but note that the default value of update_ratio in config.py is set 0.1 in this version (in previous version the update_ratio is 1). This will decrease the running time but may also decrease the performance.
