### ISSUE TITLE
how to get the pre_trained node embedding file?

### ISSUE THREAD

**Issue by MrKing8810** [hwwang55/GraphGAN#8]

**Comment by fukien** [comment]
Me too, I would like to ask for the same question

**Comment by hwwang55** [comment]
Pre-trained node embeddings can be obtained by any other network embedding method. Of course you can randomly initialize the node embeddings, but it may take you more time to fine-tune the hyper-parameters to observe a good result. In other words, a relatively "good" set of initial node embeddings can help GAN to converge better.

**Comment by fukien** [comment]
@hwwang55 Thank you for explaining the reason in detail

**Comment by fukien** [comment]
@hwwang55 Could you please tell me that what method did you use to obtain the pre-trained node embeddings.

**Comment by hwwang55** [comment]
@fukien It's DeepWalk

**Comment by fukien** [comment]
@hwwang55 Noted, thanks.
