### ISSUE TITLE
Inconsistency of Accuracy results 

### ISSUE THREAD

**Issue by SamTube405** [hwwang55/GraphGAN#9]
Hello, I experimented with your code, on running the example dataset of caGrQc for link prediction task. I could only achieve 
```
gen:0.5659075224292616
dis:0.7060041407867494
```
with the default configuration.
However, your paper reported much higher accuracy values, can you explain why?

**Comment by hwwang55** [comment]
Hi, please try fine-tuning the hyper parameters, especially the n_epochs, lr and update_ratio

**Comment by VCISwang** [comment]
请问，可以给一些fine-tuning的建议吗？通过调参，没有方向的话很难实现论文中的最终0.849的结果，甚至accuracy无法稳定提升

**Comment by lilybud** [comment]
准确率的结果下降速度很快~一开始是76%，Generator的准确率在20轮迭代之后变成了50.1%，可以请教一下原因吗？
